### ISSUE TITLE
Malformed OpenFlow packets

### ISSUE THREAD

**Issue by noproblem666** [beba-eu/beba-switch#31]
Hi,

I am using the ofsoftswitch13 from the CPqD guys for experimenting with QoS and OpenFlow meters in a Mininet environment with ryu controller. Due to the poor performance of ofsoftswitch13 I would link to use your switch in the hope that it will have better performance.  

When I run Mininet with your switch and ryu with the simple_switch13 app I get malformed packet errors in ryu. I seems that this behaviour is a result of the OpenFlow experimenter extensions which you had implemented.

Is it possible to disable this extensions in any way?

Thanks a lot!
Robert

**Comment by DavideSanvito** [comment]
Hi Robert,
which version of Ryu are you using? The one provided in our repository (https://github.com/beba-eu/beba-ctrl) or the latest Ryu?
Best,
Davide

**Comment by noproblem666** [comment]
Hi Davide, 
thanks for you quick reply. We are using the original Ryu in version 4.10.

Best,
Robert

**Comment by DavideSanvito** [comment]
Hi Robert,
we fixed the switch in the latest master by including a BEBA_STATE_ENABLED option in configure.ac file.
If you set it to 0 and compile the switch, you should be able to use our accelerated version of ofsoftswitch13 with Ryu 4.10.
If you need stateful functionalities you need to set BEBA_STATE_ENABLED to 1 and use our patched version of Ryu (based on version 3.24) which you can find at https://github.com/beba-eu/beba-ctrl/.
Let me know if you still have problems with simple_switch13 app.
Best,
David

**Comment by noproblem666** [comment]
Hi David,

thanks a lot for your message and the fix in the latest master!  

The switch is working now with Ryu 4.10 and simple_switch_13 app!

When I run a simple mininet topology with your switch I wondered about the 100% CPU load. Ping and iperf is working but the CPU load is still at 100% even if I do nothing in mininet. Is this behaviour intended in any way? 

When using iperf with TCP and default options, I will reach a bandwidth of roughly 2 Mbits/sec. Is this a valid value which you would expect? For UDP traffic the bandwidth is much higher. 

We are using queues to separate flows and we install them using dpctl tool. When running dpctl queue-mod command I will get an error: `error{type="QUEUE_OP_FAILD", code="BAD_QUEUE, dlen="56"}` although the queue will be installed correctly. 

Thanks and best,
Robert

**Comment by DavideSanvito** [comment]
Hi Robert,
for the TCP bandwidth we expect a much higher value: have you tried disabling checksum offloading for the hosts?
`ethtool --offload hX-eth0 rx off tx off`
Best,
Davide

**Comment by awgn** [comment]
Hi Robert,

We are currently trying to fix the CPU load issue, due to the active polling we adopted in order to improve the overall performance under certain condition.
CPU load is something we don't usually care about, as the software is not meat to run on a very general purpose box, but rather on a specialized middle-box.

That said, I'll try to add a compile time switch that is meant to keep the CPU low, clearly sacrificing the performance.

Best,
N.
