### ISSUE TITLE
Beba switch with floodlight controller

### ISSUE THREAD

**Issue by AliFahmy598** [beba-eu/beba-switch#54]
Does the beba switch support floodlight switch?
When I connect them, I see the controller sends the role request but beba switch sends a fail response .

**Comment by DavideSanvito** [comment]
Hi Ali,
BEBA switch is based on CPqD ofsoftswitch13. If this switch is supported by floodlight, you might be able to use our switch in floodlight but just for stateless forwarding. To program stateful behaviour you need to extend the OpenFlow protocol and API also in the controller (that's what we did in our beba-ctrl, a modified version of OSRG Ryu).
Best,
Davide

**Comment by AliFahmy598** [comment]
Can you give short overview about stateless forwarding and stateful behaviour?

**Comment by AliFahmy598** [comment]
Ok got the answer here
https://devcentral.f5.com/articles/sdn-prerequisite-stateful-versus-stateless

But could you inform me what extension necessary for openflow protocol and api to make stateful behaviour working with floodlight and bebe?

Thanks

**Comment by DavideSanvito** [comment]
BEBA switch has been developed in the context of an Europen H2020 research project.
You can find more information here http://www.beba-project.eu/.
BEBA ctrl (https://github.com/beba-eu/beba-ctrl/) already implements the required extension to make the controller able to program in-switch stateful forwarding.
If you are interested in extending floodlight, here (http://www.beba-project.eu/public_deliverables/BEBA_D2.1_Basic_BEBA_Abstraction_API.v1.0_final.pdf) you can find details about the BEBA experimenter OpenFlow extension.
Davide
